name: hippocampy

dependencies:
  - python>=3.8,<3.11
  - pip
  - mkl
  - numpy
  - numba
  - matplotlib
  - scikit-learn
  - h5py=2.10.0
  - cython
  - pip:
    - scipy
    - astropy
    - scikit-image
    - bottleneck
    - git+https://github.com/MouseLand/suite2p
    - scanimage-tiff-reader
    - mat73
    - sklearn
    - tdqm
    - pytest
    - pandas
    - git+https://github.com/j-friedrich/OASIS
    - cvxpy
    - PyWavelets
    - opencv-python