name: hippocampy

dependencies:
  - python>3.7,<3.11
  - pip
  - mkl
  - numpy
  - numba
  - matplotlib
  - scikit-learn
  - h5py
  - cython
  - pip:
    - scipy
    - astropy
    - scikit-image
    - bottleneck
    - git+https://github.com/MouseLand/suite2p
    - scanimage-tiff-reader
    - mat73
    - scikit-learn
    - tdqm
    - pytest
    - pandas
    - cvxpy
    - PyWavelets
    - opencv-python
